version: CI Build {Build}
skip_commits:
  files:
  - .github/*
  - .github/*/*
  - docs/*
  - docs/*/*
  - docs/*/*/*
  - docs-src/*
  - docs-src/*/*
  - docs-src/*/*/*
  - Scripts/*
  - .github/CONTRIBUTING.md
  - .github/FUNDING.md
  - .github/ISSUE_TEMPLATE.md
  - CODE_OF_CONDUCT.md
  - License.md
  - Logo.png
  - Readme.md
image: Visual Studio 2019
configuration:
- Debug - CUI
- Debug - GUI
- Release - CUI
- Release - GUI
platform:
- x86
- x64
before_build:
- 'echo #define NSUDO_CI_BUILD L"(CI Build %APPVEYOR_BUILD_NUMBER%)" >> %APPVEYOR_BUILD_FOLDER%\NSudo\CIBuild.h'
build:
  project: NSudo.sln
  verbosity: normal
after_build:
- >-
    7z a -r NSudo_CI_Build_%APPVEYOR_BUILD_NUMBER%.zip %APPVEYOR_BUILD_FOLDER%\Output\*.exe

    7z a -r NSudo_CI_Build_%APPVEYOR_BUILD_NUMBER%.zip %APPVEYOR_BUILD_FOLDER%\Output\*.dll

    7z a -r NSudo_CI_Build_%APPVEYOR_BUILD_NUMBER%.zip %APPVEYOR_BUILD_FOLDER%\Output\*.pdb

    7z a -r NSudo_CI_Build_%APPVEYOR_BUILD_NUMBER%.zip %APPVEYOR_BUILD_FOLDER%\Output\*.json
artifacts:
- path: NSudo_CI_Build_%APPVEYOR_BUILD_NUMBER%.zip
