version: CI Build {Build}
skip_commits:
  files:
  - '.github/**/*'
  - 'docs/**/*'
  - 'src/Documents/**/*'
  - 'Scripts/**/*'
  - '*.md'
image: Visual Studio 2019
build:
  project: src/Native/BuildAllTargets.proj
  parallel: true
after_build:
  - >-
    7z a -r NSudo_CI_Build_%APPVEYOR_BUILD_NUMBER%.zip ^
    .\src\Native\Output\*.exe ^
    .\src\Native\Output\*.dll ^
    .\src\Native\Output\*.pdb ^
    .\src\Native\Output\*.json
artifacts:
  - path: NSudo_CI_Build_%APPVEYOR_BUILD_NUMBER%.zip
